SciML/DiffEqProblemLibrary.jl

src/DiffEqProblemLibrary.jl, src/ode_premade_problems.jl
Thought it best to start a clean PR.
=> fix pleiades typo, export the function.

src/dde_premade_problems.jl
https://github.com/JuliaDiffEq/DelayDiffEq.jl/pull/61 requires these updated DDE problems (and a new release of DiffEqProblemLibrary).
=> Add parameters to history function

src/DiffEqProblemLibrary.jl, src/jump_premade_problems.jl
Adds four `JumpProblem`s to the library.
=> add JumpProblems to library

src/DiffEqProblemLibrary.jl, src/jump_premade_problems.jl
This is the first of, hopefully, several larger networks we can use for testing and benchmarking different SSAs. It is from a recently published survey that compared performance of most of the publicly available SSA simulators.
=> adding multistate network example

src/ode/ode_simple_nonlinear_prob.jl
Address changes in https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/126.
=> Mass matrix hotfix

src/dde/constant_delays.jl, src/dde/ddetst.jl, src/dde/qs.jl
Part of https://github.com/JuliaDiffEq/DelayDiffEq.jl/issues/114.
=> Change interface of analytical DDE solutions

Project.toml, src/dde/dde_premade_problems.jl, src/dde/ddetst.jl, src/dde/qs.jl, src/dde/radar5.jl
Requires version 5.15.0 of DiffEqBase with https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/283.
=> Fix and add DDE problems

src/ode/brusselator_prob.jl
=> fix Brusselator Problem

src/dde/ddetst.jl, src/dde/radar5.jl, src/ode/brusselator_prob.jl, src/ode/filament_prob.jl, src/ode/nonlinchem.jl, src/ode/ode_simple_nonlinear_prob.jl, src/ode/pollution_prob.jl, src/sde_premade_problems.jl
This makes it look good on Documenter.
=> Fix latex in docstrings

src/sde_premade_problems.jl
=> alpha-beta in SDE problem docstring

src/ode/ode_simple_nonlinear_prob.jl
=> Fixed typo in vanstiff docstring

src/dde/radar5.jl
Fix history function docstring ```ϕ_5``` for **prob_dde_RADAR5_waltman**
=> Fix radar5 docstring

lib/JumpProblemLibrary/Project.toml, lib/JumpProblemLibrary/src/JumpProblemLibrary.jl, lib/ODEProblemLibrary/Project.toml, lib/ODEProblemLibrary/src/ODEProblemLibrary.jl, lib/SDEProblemLibrary/Project.toml, lib/SDEProblemLibrary/src/SDEProblemLibrary.jl
Can revert later when this is fixed.
=> Remove precompilation for MTK support

lib/DAEProblemLibrary/src/DAEProblemLibrary.jl
This PR adds the DAE test problem in https://archimede.uniba.it/~testset/testsetivpsolvers/?page_id=26, part of the issue of #17 
```julia
prob = DAEProblem(transamp, du0, u0, tspan)
sol = solve(prob, DFBDF())
```
=> Add transistor amplifier DAE problem

lib/BVProblemLibrary/src/BVProblemLibrary.jl, lib/DAEProblemLibrary/src/DAEProblemLibrary.jl, lib/DDEProblemLibrary/src/DDEProblemLibrary.jl, lib/DDEProblemLibrary/src/constant_delays.jl, lib/DDEProblemLibrary/src/ddetst.jl, lib/DDEProblemLibrary/src/radar5.jl, lib/JumpProblemLibrary/src/JumpProblemLibrary.jl, lib/ODEProblemLibrary/src/ODEProblemLibrary.jl, lib/ODEProblemLibrary/src/brusselator_prob.jl, lib/ODEProblemLibrary/src/filament_prob.jl, lib/ODEProblemLibrary/src/nonlinchem.jl, lib/ODEProblemLibrary/src/ode_linear_prob.jl, lib/ODEProblemLibrary/src/ode_simple_nonlinear_prob.jl, lib/ODEProblemLibrary/src/pollution_prob.jl, lib/SDEProblemLibrary/src/SDEProblemLibrary.jl
Fix #16 
Reference: https://archimede.uniba.it/~bvpsolvers/testsetbvpsolvers/?page_id=29
=> Add the rest BVP test prblems

lib/SDEProblemLibrary/src/SDEProblemLibrary.jl
Now the SDE constructor is simply ```SDEProblem(SDEFunction(f, g), u0, tspan)``` or ```SDEProblem(f, g, u0, tspan)```
https://github.com/SciML/SciMLBase.jl/pull/489
=> Refactor SDEProblem constructor

lib/BVProblemLibrary/Project.toml, lib/BVProblemLibrary/src/BVProblemLibrary.jl, lib/BVProblemLibrary/src/linear.jl, lib/BVProblemLibrary/src/nonlinear.jl
Refactor test problems in BVProblemLibrary with new API
=> Refactor BVProblemLibrary with new constructor

lib/BVProblemLibrary/Project.toml, lib/BVProblemLibrary/src/BVProblemLibrary.jl, lib/BVProblemLibrary/src/linear.jl, lib/BVProblemLibrary/src/nonlinear.jl
Fix some mistakes in BVProblemLibrary
=> Fix bugs in BVP test problems

lib/NonlinearProblemLibrary/Project.toml, lib/NonlinearProblemLibrary/src/NonlinearProblemLibrary.jl
Now we have solvers which pass on all problems :tada:
=> Patch Watson Function

lib/JumpProblemLibrary/src/JumpProblemLibrary.jl, lib/ODEProblemLibrary/src/ODEProblemLibrary.jl
=> Precompile the problem libraries again

lib/BVProblemLibrary/Project.toml, lib/BVProblemLibrary/src/nonlinear.jl
Some parameters are not correct and we should use a good initial guess for the problem.
Also, the package version is bumped, just need register and release
=> Fix parameters in prob_bvp_nonlinear_6
