SciML/DiffEqProblemLibrary.jl

src/DiffEqProblemLibrary.jl, src/dde_premade_problems.jl
Hi!
I discovered that the analytical solution to one of the test problems in `DelayDiffEq.jl` is incorrect. The errors in https://github.com/JuliaDiffEq/DelayDiffEq.jl/blob/master/test/constrained.jl#L32 and https://github.com/JuliaDiffEq/DelayDiffEq.jl/blob/master/test/constrained.jl#L81 do not affect the calculations since they occur outside of the time interval of the corresponding DDE problems. Nevertheless, I thought it could be beneficial to add the most used test problems in `DelayDiffEq.jl` to this repository, in order to remove redundancy and possible additional errors.
I recalculated both analytical solutions in https://github.com/JuliaDiffEq/DelayDiffEq.jl/blob/master/test/constrained.jl with Mathematica.
=> Add some DDE problems from DelayDiffEq.jl

src/DiffEqProblemLibrary.jl, src/dde_premade_problems.jl
This improves existing problems by making both functions and solutions compatible with units and adds additional DDE problems. Most examples are taken from W.H. Enright and H. Hayashi, The evaluation of numerical software for delay differential equations. I'm not sure whether parameters and variables of `prob_dde_qs` should be changed to similar scales for testing purposes - otherwise even huge differences in variables that are very small in absolute values won't affect the overall error, I guess?
=> Improve and add DDE problems

src/DiffEqProblemLibrary.jl, src/jump_premade_problems.jl
Here I've added two networks that were used in (published) SSA benchmarks. This should ultimately help us see how our implementations are performing relative to the published benchmarks (for example, due to priority queue issues the NRM is performing much poorer relative to the direct method that is seen in the published benchmarks).
The specific networks added here are
1. Negative feedback auto-regulatory gene expression model, where feedback is by dimers of the expressed protein.
2. A 20 gene network with switching behavior that was used as an example where the sorting direct method can greatly outperform the direct method.
=> added jump examples used in benchmarking

src/DiffEqProblemLibrary.jl, src/jump_premade_problems.jl
Used in the Benchmarks I've started putting together (which I'll submit once this is merged).
=> add diffusion by CTRW example

src/jump_premade_problems.jl, src/sde_premade_problems.jl
This is no longer supported by DEBio since we just return a `ReactionSystem` now.
=> update reaction_network to remove custom types

Project.toml, src/jump_premade_problems.jl, src/sde_premade_problems.jl
The jumps all load now (locally at least), but I haven't tested them much for accuracy yet.
=> update jump problems for catalyst

Project.toml, src/ode/ode_simple_nonlinear_prob.jl
See https://en.wikipedia.org/wiki/Van_der_Pol_oscillator#Two-dimensional_form
=> Fix Van der Pol equations

.github/workflows/CI.yml, lib/DAEProblemLibrary/Project.toml, lib/DAEProblemLibrary/test/runtests.jl, lib/DDEProblemLibrary/Project.toml, lib/DDEProblemLibrary/src/DDEProblemLibrary.jl, lib/DDEProblemLibrary/test/runtests.jl, lib/JumpProblemLibrary/Project.toml, lib/JumpProblemLibrary/test/runtests.jl, lib/ODEProblemLibrary/Project.toml, lib/ODEProblemLibrary/test/runtests.jl, lib/SDEProblemLibrary/Project.toml, lib/SDEProblemLibrary/test/runtests.jl
When I removed the deprecations in DDEProblemLibrary, I did not notice that the exports were outdated and some of them are undefined. I added tests for this, also to other packages.
=> Fix and test undefined exports

lib/DDEProblemLibrary/Project.toml, lib/DDEProblemLibrary/src/constant_delays.jl
Seems I managed to introduce a bug... This should fix the test failures in https://github.com/SciML/DelayDiffEq.jl/pull/240.
=> Fix bug in `prob_dde_constant_2delays_oop`

lib/ODEProblemLibrary/src/ODEProblemLibrary.jl, lib/ODEProblemLibrary/src/ode_simple_nonlinear_prob.jl
Fixes #96
I also added `prob_ode_lotkavolterra` and `prob_ode_fitzhughnagumo` to the exports, since it seemed a bit arbitrary that those two are not exported but most (all?) others are. Let me know if I should revert this. 
Also: **Should I increase the version of ODEProblemLibrary as part of this PR, or is that handled separately?**
Thanks!
=> Correct spelling of Lotka-Volterra

lib/ODEProblemLibrary/src/strange_attractors.jl
Needed to get rid of a warning for strict links in DiffEqDocs.
=> [skip ci] fix link warning

lib/JumpProblemLibrary/Project.toml, lib/JumpProblemLibrary/src/JumpProblemLibrary.jl
So we can update the Benchmarks to Catalyst 13 too...
=> Update jump problems to Catalyst 13

lib/BVProblemLibrary/Project.toml, lib/BVProblemLibrary/src/linear.jl
Fix 13th and 17th linear BVP test problems.
Error in 13th: The boundary condition on $u(1)$ should be $\exp(-2/\sqrt{\lambda})$
Error in 17th: The derivative of analytical solution should be $z'(t)=1/\sqrt{λ + t^2} - t^2 / (λ + t^2)^{(3 / 2)}$
Related to https://github.com/SciML/SimpleBoundaryValueDiffEq.jl/pull/4
=> Fix 13th and 17th BVP test problems

lib/JumpProblemLibrary/Project.toml, lib/JumpProblemLibrary/src/JumpProblemLibrary.jl
Note this is breaking and will likely break one or more SciMLBenchmarks that use this code.
=> update jumps for Catalyst 14

.github/workflows/CI.yml, .github/workflows/FormatCheck.yml, .github/workflows/Invalidations.yml
Update the workflows in this repository to use SciML's reusable workflows.
This is part of a larger effort to standardize the SciML's CI workflows for more generic and common requirements, to keep the workflows uniform and easier to maintain.
=> ci: standardize workflows using SciML's reusable workflows

lib/ODEProblemLibrary/Project.toml, lib/ODEProblemLibrary/src/ode_simple_nonlinear_prob.jl
This was using an old form that didn't necessarily always get the order right. This PR fixes the constructors to ensure they are safe for any equation reordering, and thus fixes downstream.
=> Properly use symbolic constructors

lib/ODEProblemLibrary/Project.toml, lib/ODEProblemLibrary/src/ODEProblemLibrary.jl, lib/ODEProblemLibrary/src/ode_simple_nonlinear_prob.jl, lib/ODEProblemLibrary/src/strange_attractors.jl
[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
[COLPRAC](https://github.com/SciML/COLPRAC).
Add any other context about the problem here.
=> refactor: update to MTKv10

lib/ODEProblemLibrary/Project.toml
MTK v9 and v10 are not mutually usable, so if we support MTK v10, we aren't supporting MTK v9 anymore.
I still think that MTK v10 support should be a major verison bump here, but oh well.
=> stop supporting MTK@9

lib/BVProblemLibrary/src/BVProblemLibrary.jl
None applicable
[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
[COLPRAC](https://github.com/SciML/COLPRAC).
Fix `frac` to `\frac`
=> Fix backslash in TeX in BVProblemLibrary.jl

lib/ODEProblemLibrary/src/brusselator_prob.jl, lib/ODEProblemLibrary/src/ode_simple_nonlinear_prob.jl, lib/ODEProblemLibrary/src/pollution_prob.jl, lib/ODEProblemLibrary/src/strange_attractors.jl
The docstrings are TeX-heavy, and this allows easier writing of backslashes.
=> Use `@doc_str` macro for docstrings

lib/JumpProblemLibrary/src/JumpProblemLibrary.jl
Make sure that sentence text is not picked up as code examples by doc formatters and viewers.
=> Dedent docstrings in JumpProblemLibrary
